version: 2.1

jobs:
    build-and-test:
        machine:
          node:
            version: 0.10
        test:
          override:
            - ./node_modules/.bin/mocha

workflows:
    main:
        jobs:
            - build-and-test
