version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     
     # build the application image
     - run: docker build -t hello-ci-workflow .

     # deploy the image
     - run: docker run -d -p 3000:3000 hello-ci-workflow; sleep 10
     # 使用 curl 測試 docker 是否有順利執行 node
     - run: curl --retry 10 --retry-delay 5 -v http://localhost:3000

# test with curl