version: 2.1

jobs:
    build-and-test:
        machine:
            node:
                version: 12.16.0
            test:
                - npm test

workflows:
    main:
        jobs:
            - build-and-test
